### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601-F17/iteration-2-cheezit#66]
This mainly is about Firebase Cloud Firestore rules

**Comment by EthanUphoff** [comment]
Things that need to be worked on as of 194a5a293798d47f57e70a670dead55c18f62c7b:
- [ ] Teachers should not be able to add students themselves, students need to join themselves.
- [x] Users should not be able to move their decks to classes they are not in and are not teachers in.
- There are probably more things that need to be done.
